### ISSUE TITLE
Add Code Standards/Style Guide Specifications to the Wiki

### ISSUE THREAD

**Issue by L00166967** [ruthlennonatu/bsc23Hurlfit#109]
I'm gonna do so in the document branch and ask the team to look it over before I push to main.

Subtask of #63.

**Comment by L00166967** [comment]
I'm also going to make a Code Standards document in a new Documentation folder at the root of the repo.

**Comment by L00166967** [comment]
It'll be under code_standards.txt

**Comment by L00166967** [comment]
Added first draft. @aaronbonnerATU Can you take a look at this, since this might be relevant to testing?

**Comment by aaronbonnerATU** [comment]
Seems ok to me add it to the wiki anyways so if it is relevant to testing I can see.
