### ISSUE TITLE
Developer : Design : front end : Home page,registration page,user profile, booking page

### ISSUE THREAD

**Issue by Shashanksanap99** [ruthlennonatu/bsc23Hurlfit#45]
As a developer, we will need a home page, registration page, user profile page, login page, and booking page.

**Comment by L00129014** [comment]
Going to create a design doc with the layout for each page.

**Comment by Shashanksanap99** [comment]
Can you please share me design for the login page, So I can make HTML page for it

**Comment by L00129014** [comment]
Will have it uploaded later on tonight, it can be assigned tomorrow.

**Comment by Shashanksanap99** [comment]
- [ ] Create login, Signup page : Commit for this is :- 6f5fb2d
- [ ] Create Home page
- [ ] Create Booking page
- [ ] Create user profile
