### ISSUE TITLE
Properly decide on the tools we will use.

### ISSUE THREAD

**Issue by L00166967** [ruthlennonatu/bsc23Hurlfit#58]
Not just the language/testers, everything.

**Comment by Shashanksanap99** [comment]
Here is the basic checklist that we should think of 

1. CI/CD tool 
2. Infrastructure environment
3. Configuration management tool 
4. Monitoring tool
5. Deployment tool
6. Documentation
7. Version control
8. Unit testing
9. Testing tool
10. Security tool

Everyone can comment on what we can use and we can discuss it as well one by one.

**Comment by Shashanksanap99** [comment]
- [ ] CI/CD tool  - Github Actions
- [ ] Performance Management tool
- [ ] SAST AND DAST -
- [ ] Deployment - 
- [ ] Documentation
- [ ] Version control  - Github
- [ ] Unit testing - MOCHA
- [ ] Testing tool - Selenium
Everyone can comment on and update as we decide
